include:
  - path:
      - ./chat-infra/compose.yml

services:
  chat-api-command:
    build:
      context: ..
      dockerfile: chat/cmd/api-command/Dockerfile
    image: boardroom/api-command:latest
    environment:
      PORT: "8080"
      KAFKA_BROKERS: host.docker.internal:9092
    restart: unless-stopped
#    depends_on:
#      - kafka

  chat-api-query:
    build:
      context: ..
      dockerfile: chat/cmd/api-query/Dockerfile
    image: boardroom/api-query:latest
    environment:
      PORT: "8081"
      SCYLLA_HOST: scylla
    restart: unless-stopped
    depends_on:
      scylla:
        condition: service_healthy

  chat-ws:
    build:
      context: ..
      dockerfile: chat/cmd/ws/Dockerfile
    image: boardroom/ws:latest
    environment:
      PORT: "8082"
      REDIS_ADDR: redis:6379
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy

  chat-consumer-notifier:
    build:
      context: ..
      dockerfile: chat/cmd/consumer-notifier/Dockerfile
    image: boardroom/consumer-notifier:latest
    environment:
      KAFKA_BROKERS: host.docker.internal:9092
      REDIS_ADDR: redis:6379
    restart: unless-stopped
    depends_on:
#      - kafka
      redis:
        condition: service_healthy

  chat-consumer-chat:
    build:
      context: ..
      dockerfile: chat/cmd/consumer-chat/Dockerfile
    image: boardroom/consumer-chat:latest
    environment:
      KAFKA_BROKERS: host.docker.internal:9092
      SCYLLA_HOST: scylla
    restart: unless-stopped
    depends_on:
#      - kafka
      scylla:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chat-api-command
      - chat-api-query
      - chat-ws