services:
  chat-api-command:
    build:
      context: ..
      dockerfile: backend/chat/cmd/api-command/Dockerfile
    image: boardroom/api-command:latest
    environment:
      PORT: "8080"
      KAFKA_BROKERS: host.docker.internal:9092
    ports:
      - "8080:8080"
    restart: unless-stopped

  chat-api-query:
    build:
      context: ..
      dockerfile: backend/chat/cmd/api-query/Dockerfile
    image: boardroom/api-query:latest
    environment:
      PORT: "8081"
      SCYLLA_HOST: host.docker.internal
    ports:
      - "8081:8081"
    restart: unless-stopped

  chat-ws:
    build:
      context: ..
      dockerfile: backend/chat/cmd/ws/Dockerfile
    image: boardroom/ws:latest
    environment:
      PORT: "8082"
      REDIS_ADDR: host.docker.internal:6379
    ports:
      - "8082:8082"
    restart: unless-stopped

  chat-consumer-notifier:
    build:
      context: ..
      dockerfile: backend/chat/cmd/consumer-notifier/Dockerfile
    image: boardroom/consumer-notifier:latest
    environment:
      KAFKA_BROKERS: host.docker.internal:9092
      REDIS_ADDR: host.docker.internal:6379
    restart: unless-stopped

  chat-consumer-chat:
    build:
      context: ..
      dockerfile: backend/chat/cmd/consumer-chat/Dockerfile
    image: boardroom/consumer-chat:latest
    environment:
      KAFKA_BROKERS: host.docker.internal:9092
      SCYLLA_HOST: host.docker.internal
    restart: unless-stopped

